
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

target 'VOLCDemo' do
  # vod SDK
  pod 'TTSDK', '1.32.1.1-premium', :subspecs => ['Player']
  # vod all scene exhibition
  pod 'VEPlayModule', :path=> './VEPlayModule/' 
  # vod player kit
  pod 'VEPlayerKit', :path=> './VEPlayerKit/'
  # vod player control UI kit
  pod 'VEPlayerUIModule', :path=> './VEPlayerUIModule/'
  # vod short scene kit
  pod 'VESceneKit', :path=> './VESceneKit/'
  
  # public SDK
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Reachability'
  pod 'JSONModel'
  
end

