
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

target 'VOLCDemo' do
  pod 'TTSDK', '1.27.2.1-premium', :subspecs => ['Player']
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Reachability'
  pod 'MJRefresh'
  
end

