
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '11.0'

target 'VOLCDemo' do
  # vod SDK
  pod 'TTSDK', '1.39.1.14-premium', :subspecs => ['Player']
  # vod all scene exhibition
  pod 'VEPlayModule', :path=> './VEPlayModule/' 
  # vod player kit
  pod 'VEPlayerKit', :path=> './VEPlayerKit/'
  # vod player control UI kit
  pod 'VEPlayerUIModule', :path=> './VEPlayerUIModule/'
  # vod short scene kit
  pod 'VESceneKit', :path=> './VESceneKit/'
  
  
  
  # public SDK
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Reachability'
  pod 'JSONModel'
  pod 'YYKit'

end

# xcode14 code sign
post_install do |installer|
  [installer.generated_projects, installer.pods_project]
  .flatten.map{ |p| p.targets}
  .flatten.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CODE_SIGN_IDENTITY"] = "-"
        config.build_settings["CODE_SIGN_ENTITLEMENTS"] = "-"
        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
        config.build_settings["CODE_SIGNING_REQUIRED"] = "NO"
    end
  end
end
